### ISSUE TITLE
如何设置列名

### ISSUE THREAD

**Issue by zhangyongbo** [cuikangjie/JsonExportExcel#1]
可否为2个参数，第一个为列名的数组（可选），第二个为书籍对象或数组

**Comment by ivan-lee** [comment]
var header = {
                    COL1: “列1"
                , COL2: “列2"
                , COL3: “列3"
                };
                data.unshift(header);


这样就可以设置列名了

**Comment by zhangyongbo** [comment]
我试了下Safari、IE8、9都不支持

**Comment by ivan-lee** [comment]
确实不能支持Safari   你有找到支持这些浏览器的代码吗    分享下 @zhangyongbo
